/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import videoField from "@sklinet/strapi-plugin-video-field/strapi-admin";
import seo from "@strapi-community/plugin-seo/strapi-admin";
import documentation from "@strapi/plugin-documentation/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import dragDropContentTypesStrapi5 from "@yunusemrejs/drag-drop-content-types-strapi5/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.tsx";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    "video-field": videoField,
    seo: seo,
    documentation: documentation,
    "users-permissions": usersPermissions,
    "drag-drop-content-types-strapi5": dragDropContentTypesStrapi5,
    "config-sync": configSync,
  },
});
